### ISSUE TITLE
Supporting a json response

### ISSUE THREAD

**Issue by Hanako999** [NonFactors/MVC.Grid#5]
Hi, I like so much this plugin!

I use Paging, Sorting and Filtering.
Now,  My web page relocate by using "_Grid" partial view or read only my partial view by using "_AjaxMvcGrid" partial view.
But, I want to get my data in Json, not a partial view.
(Reloading  a partial view is worse parformance than reloading json data....:-( )
Is there how to use "MVC.Grid" by getting Json data when Paging, Sorting and Filtering??

(My English is not good but hope you understand me.....!)

**Comment by Muchiachio** [comment]
Hmm, I don't think that loading grid from JSON data could be achieved without major changes to the [mvc-grid.js](https://github.com/NonFactors/MVC.Grid/blob/develop/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js) file. Mainly because grid is being defined inside a razor view and not returned from a controller.

Did you identified this to be your application's bottleneck?

**Comment by Hanako999** [comment]
Thanks for the response!

Now, that isn't my application's bottleneck.
I think this plugin is more useful if i can use not only a partial view but also JSON data.
So I asked the question.

**Comment by Muchiachio** [comment]
Ah, okay. Sorry, but I will not be doing this for now (maybe this later with MVC6, because tag helpers seems promising for this type of stuff), because it would require a lot of API and code changes now.

Thanks for feedback.
